/-
M5 Formalization-Ready Definitions (FRDs) — SCAFFOLD
======================================================

Generated by SIARC relay 098 (T2-FRD-EXPORT-FROM-M5-098) on 2026-05-07.

Substrate anchors:
  picture_v1.19.md      SHA-256
    8BD9043370872F078F05DE99AC031A8AE78C321EC75F49102ABC01F549326DAB
    (sessions/2026-05-06/PICTURE-V19-CONSOLIDATED-DEPOSIT/picture_v1.19.md;
    M5 milestone row at line 919; § 4 "Milestones to Reach")

  PCF-1 v1.3 source     SHA-256
    82173A09521D6676ADC523E1D55CD1310F693479608A9F98EB980689A4786853
    (tex/submitted/p12_journal_main.tex)

  Bridge HEAD           dbe7a71abcea953c2c5cf85dc47970714d34ced1
                        (siarc-relay-bridge at fire time)

Coefficient-ordering convention
-------------------------------
This file uses the SIARC F(2,4) leading-first coefficient convention
recorded in repo memory `f1-base-d2d4-complete-2026-04-22`, namely

    a_coeffs = (a2, a1, a0)   with   a(n) = a2 * n^2 + a1 * n + a0
    b_coeffs = (b1, b0)       with   b(n) = b1 * n + b0

This is the convention of `f1_base_computation.py` and the relay 098
spec (Phase B B1). PCF-1 v1.3 (the published transcendence-dichotomy
paper p12) uses the inverse role convention (a degree 1, b degree 2)
under names (alpha, beta, gamma, delta, epsilon). The two conventions
enumerate the same d=2 PCF family up to a label swap a <-> b; see
`discrepancy_log.json` D-D3 for the explicit translation table.

Status
------
SCAFFOLD only. Proof bodies are `sorry` and inductive predicates are
`Prop`-level skeletons. Subsequent fires (e.g. M10-PROOF-DRAFT) iterate
proofs and tighten Mathlib4 anchors per `mathlib4_anchor_opportunities.md`.

Reviewer-D BS-Lean4 grounding
-----------------------------
This scaffold addresses the 4-of-4 peer-AI synthesis blind-spot finding
that M10 (Lean formalization) lacks evidence the math in M1-M9 is
formally checkable. FRD export from M5 begins here; sorries are tagged
with the responsible substrate anchor for downstream relay fires.
-/

-- Mathlib4 imports (minimal scaffold; full anchor pass deferred to
-- mathlib4_anchor_opportunities.md per relay E.E3).
-- TODO: identify exact Mathlib4 import for continued fractions when
-- B6 / B8 proof bodies are populated; current candidates per Mathlib4
-- module browser are `Mathlib.Algebra.ContinuedFractions.Basic` and
-- `Mathlib.NumberTheory.ContinuedFractions.Basic`. See E.E3 row B6.
import Mathlib.Tactic
import Mathlib.Data.Real.Basic
import Mathlib.Data.Rat.Defs

namespace SIARC.M5

-- ============================================================
-- B1.  V_quad family (5-parameter rational tuple)
-- ============================================================

/--
The 5-parameter family of degree-two PCFs in SIARC F(2,4) convention,
with `a` of degree 2 in the index and `b` of degree 1.

  a(n) = a2 * n^2 + a1 * n + a0
  b(n) = b1 * n + b0

Substrate anchors:
  picture_v1.19.md line 919  (M5 milestone row "V_quad -> P_III(D_6)")
  PCF-1 v1.3       § 1.1     (transcendence predicate; d=2 class
                              equation labelled `eq:d2-class`)

The label `VQuad` denotes the parameter manifold; concrete strata
(Trans / Alg / Rat / Log) are carved out via `stratumOf` (B4).
-/
structure VQuad where
  a2 : ℚ
  a1 : ℚ
  a0 : ℚ
  b1 : ℚ
  b0 : ℚ
deriving Repr, DecidableEq

namespace VQuad

/--
Polynomial evaluation of `a` at a rational index `n`, per the
leading-first convention `a(n) = a2 n^2 + a1 n + a0`.
-/
def aPoly (V : VQuad) (n : ℚ) : ℚ := V.a2 * n^2 + V.a1 * n + V.a0

/--
Polynomial evaluation of `b` at a rational index `n`, per the
leading-first convention `b(n) = b1 n + b0`.
-/
def bPoly (V : VQuad) (n : ℚ) : ℚ := V.b1 * n + V.b0

end VQuad

-- ============================================================
-- B2.  R(h) ratio
-- ============================================================

/--
Stratum tag for the d=2 PCF transcendence dichotomy. Mirrors the
3-stratum partition refined in picture_v1.19.md lines 295-298
(neg-rational `a_1`, pos-rational `a_1`, `a_1 = 0`) plus the Trans
side recorded in PCF-1 v1.3 § 4 Table 1 (`tab:dichotomy`).

Members:
  * `trans`   — Delta > 0 Trans stratum (e.g. F(2,4) Trans table)
  * `alg`     — algebraic non-rational stratum
  * `rat`     — rational stratum
  * `log`     — logarithmic stratum (e.g. ln 2 family)
  * `phantom` — phantom / unclassified residual stratum
-/
inductive Stratum where
  | trans
  | alg
  | rat
  | log
  | phantom
deriving Repr, DecidableEq

/--
Pointwise ratio `R(h) = b(h) / a(h)` at a rational parameter `h`.

Substrate anchors:
  picture_v1.19.md lines 295-298  (3-stratum partition at 60+ digits)
  PCF-1 v1.3       § 1.1 lines 109-116  (PCF schema; ratio interpretation)

Convention note: branching by stratum is captured separately by
`stokes` (B4). The bare ratio `R` is total over rationals where
`aPoly h ≠ 0`; the `aPoly h = 0` case is left to a subsequent fire
(see `discrepancy_log.json` D-D2 partial-function audit).
-/
def R (V : VQuad) (h : ℚ) : ℚ := V.bPoly h / V.aPoly h

-- ============================================================
-- B3.  Indicial polynomial + double-root condition
-- ============================================================

/--
The indicial polynomial of the d=2 family is the leading-coefficient
polynomial in the Wallis recurrence, evaluated as a function `ℚ → ℚ`:

    indicialPoly V (u) = a2 * u^2 + a1 * u + a0

Substrate anchors:
  picture_v1.19.md line 91  (Wimp-Zeilberger Newton-polygon convention)
  PCF-1 v1.3       § 2.1    (Perron-Poincare characteristic eq:char;
                            balanced discriminant Delta = beta^2 - 4 alpha gamma
                            translates under the a <-> b label swap to the
                            indicial discriminant a1^2 - 4 a2 a0 used here)
-/
def indicialPoly (V : VQuad) (u : ℚ) : ℚ :=
  V.a2 * u^2 + V.a1 * u + V.a0

/--
Double-root condition for the indicial polynomial:

    a1^2 = 4 * a2 * a0

This is the algebraic locus where `indicialPoly V` has a double root,
equivalently where the indicial discriminant `a1^2 - 4 a2 a0` vanishes.
This locus is the SIARC analogue of the borderline case discussed in
picture_v1.19.md § G23 (lines 97-98) where the SIARC stratum sits at
the boundary between Wimp-Zeilberger normal and anormal cases.
-/
def doubleRootCondition (V : VQuad) : Prop :=
  V.a1^2 = 4 * V.a2 * V.a0

/--
The indicial discriminant of the d=2 family, equal to
`a1^2 - 4 * a2 * a0` and named in alignment with the balanced
discriminant `Delta = beta^2 - 4 alpha gamma` of PCF-1 v1.3
Definition 4.1 (`def:Delta`) under the a <-> b label swap.
-/
def indicialDiscriminant (V : VQuad) : ℚ :=
  V.a1^2 - 4 * V.a2 * V.a0

-- ============================================================
-- B4.  Stokes data per stratum
-- ============================================================

/--
Stokes-multiplier metadata returned by `stokes`. The two fields
encode the per-rep Stokes-side observables recorded numerically in
picture_v1.19.md lines 347-353 (Prompt 010 verdict
`G6B_PARTIAL_HIGHER_ORDER_NEEDED`):

  * `sign`   — sign of the leading Stokes constant `C` per rep
                (e.g. V_quad C > 0; QL09 C < 0)
  * `parity` — parity tag for the alien-amplitude branch
                (0 = principal, 1 = conjugate); placeholder for
                the connection-coefficient parity audit.
-/
structure StokesData where
  sign : Int
  parity : Nat
deriving Repr, DecidableEq

/--
Stratum classifier. Returns the SIARC `Stratum` tag for a parameter
point. Substantive content (the algebraic predicates carving out
each stratum) is left as `sorry` in this scaffold and tracked in
`coverage_gap_analysis.md` row B4 for a subsequent relay fire.

Substrate anchors:
  picture_v1.19.md lines 295-298 + 313-318  (a_1 partition + G20)
  PCF-1 v1.3       § 5            (Stokes-exponent diagnostic)
-/
def stratumOf (V : VQuad) : Stratum := sorry

/--
Per-stratum Stokes data, stratified by `stratumOf`. The leading
Stokes constants `S_1 = 2 * pi * i * C` per rep are recorded in
picture_v1.19.md line 348 to >= 49 digits; this scaffold leaves
the closed-form Stokes-data assignment as `sorry`.
-/
def stokes (V : VQuad) : StokesData := sorry

-- ============================================================
-- B5.  zeta_star (target convergence value)
-- ============================================================

/--
The Borel-plane convergence parameter `zeta_*` for the leading
Birkhoff-resurgent ansatz `a_n ~ C * Gamma(n) * zeta_*^{-n}`.

Substrate anchors:
  picture_v1.19.md line 360  (V_quad zeta_* = 4 / sqrt(3) exact)
  PCF-1 v1.3       § 6       (V_quad P_III(D_6) prototype)

Per-rep concrete values from picture_v1.19.md and CC-MEDIAN-RESURGENCE-EXECUTE
substrate:

  V_quad : zeta_*      = 4 / sqrt(3)        (exact algebraic)
  QL15   : zeta_*      = computed dps>=300  (numeric anchor)
  QL05   : zeta_*      = computed dps>=300  (numeric anchor)
  QL09   : zeta_*      = computed dps>=300  (numeric anchor)

The closed-form algebraic case (V_quad) requires the Mathlib4 anchor
for algebraic numbers; see `mathlib4_anchor_opportunities.md` row B5.
-/
noncomputable def zetaStar (V : VQuad) : ℝ := sorry

-- ============================================================
-- B6.  PCF limit operator  L = b(0) + K
-- ============================================================

/--
The continued-fraction limit `L = b(0) + K(a_n / b_n)` where `b(0)`
is the constant term of the `b` polynomial added OUTSIDE the K-fold,
per the conventional Wallis-seed expansion of PCF-1 v1.3 § 1.1
equation `eq:PCF`:

    L = b_0 + a_1 / (b_1 + a_2 / (b_2 + ...))

In the SIARC F(2,4) convention `b(0) = b0` is the constant offset.
Convergence depends on the Perron-Poincare structure of the d=2
family; the Lean type is `ℝ` (the formal real) since the limit is
in general transcendental.

Substrate anchors:
  picture_v1.19.md line 919   (M5 milestone V_quad -> P_III(D_6))
  PCF-1 v1.3       § 1.1      (eq:PCF; Wallis recurrence convention)

The body is `sorry`; substantive content depends on a Mathlib4
continued-fraction anchor (see `mathlib4_anchor_opportunities.md`
row B6).
-/
noncomputable def PCFLimit (V : VQuad) : ℝ := sorry

-- ============================================================
-- B7.  M8b axis residual acceptance (forward-link to relay 092)
-- ============================================================

/--
Statement-only stub for the M8b axis sub-leading Stokes constant
`S_2` permanent-residual verdict per relay 092 (T1-017M-BOREL-PADE-S2-092)
verdict label `M8b_S2_PERMANENT_RESIDUAL_VIA_BOREL_PADE`.

Substrate anchors:
  picture_v1.19.md M8b row (lines 1031-1041)
  Relay session            sessions/2026-05-07/T1-017M-BOREL-PADE-S2-092/
                           handoff.md (15 AEAL claims; 196 cells; 0 RANK_LOSS)

The proposition placeholder `True` is intentional: the M8b axis
verdict is a numerical-permanent-residual claim, not a closed-form
identity, and the Lean encoding of "permanent residual at given
precision" requires a quantitative real-analysis predicate that is
out of scope for this scaffold. A subsequent fire (M10-PROOF-DRAFT
or a dedicated M8b formalization fire) will refine the statement.
-/
theorem M8b_axis_residual_acceptance (V : VQuad) : True := by
  trivial

-- ============================================================
-- B8.  Wallis recurrence
-- ============================================================

/--
One step of the Wallis recurrence

    p_n = b_n * p_{n-1} + a_n * p_{n-2}

with `b_n = bPoly V (n : ℚ)` and `a_n = aPoly V (n : ℚ)`. This is
the fundamental linear-recurrence engine of the d=2 PCF; the
convergent sequence `p_n / q_n` produces the value of the PCF.

Substrate anchors:
  picture_v1.19.md line 91     (Newton-polygon analysis convention)
  PCF-1 v1.3       § 2.1       (Wallis recurrence eq:wallis)
-/
def wallisStep (V : VQuad) (n : ℕ) (pPrev pPrev2 : ℚ) : ℚ :=
  V.bPoly (n : ℚ) * pPrev + V.aPoly (n : ℚ) * pPrev2

/--
Numerator sequence of the Wallis recurrence with seeds
`(p_{-1}, p_0) = (1, b_0)` per PCF-1 v1.3 § 1.1. The `n+2` body
is `sorry`; a subsequent fire (M10-PROOF-DRAFT or a Wallis-recurrence
discharge fire) populates it.
-/
def wallisP (V : VQuad) : ℕ → ℚ
  | 0 => V.b0
  | 1 => V.b1 + V.b0 * V.a1   -- placeholder; substantive at n+2 below
  | _ + 2 => sorry

-- ============================================================
-- B9.  Spec(K) classification 5-tuple
-- ============================================================

/--
The Spec(K) invariant of PCF-1 v1.3 § 2.2 (`ssec:speck`,
equation `eq:speck`) is a 5-tuple

    Spec(K) = (d, Lambda, Delta, rho, tau)

with:

  * `d`      — dominant growth degree of the family
  * `lambda` — normalised Perron-Poincare root
  * `delta`  — balanced discriminant
  * `rho`    — Wallis tail-decay rate (digits per step)
  * `tau`    — arithmetic sector tag (encoded as `Stratum` here)

Substrate anchors:
  picture_v1.19.md line 41   (Spec(K) classification reference)
  PCF-1 v1.3       § 2.2     (Spec(K) 5-tuple definition)

The arithmetic-sector field is `Stratum` rather than the published
`tau : ℕ` to align with the SIARC stratum terminology of B4. The
two encodings are inter-convertible via a finite enumeration map
(out of scope for this scaffold; see `coverage_gap_analysis.md`
row B9).
-/
structure SpecK where
  d : ℕ
  lambda : ℝ
  delta : ℝ
  rho : ℝ
  tau : Stratum
deriving Repr

/--
Compute the Spec(K) 5-tuple of a parameter point. Body is `sorry`
pending closed-form evaluation of `lambda` and `rho` for the d=2
family; substrate values for `lambda` per rep are recorded in
picture_v1.19.md (V_quad: Lambda in `Q(sqrt(alpha^2 + 4 delta))` per
PCF-1 v1.3 eq:char).
-/
noncomputable def specK (V : VQuad) : SpecK := sorry

end SIARC.M5
