#!/usr/bin/env python3
# PERIOD-REP-VQUAD-003 Stage 0.1 — INDEPENDENT L_V residual confirmation.
#
# VQUAD-002 verified L_V . B-hat = 0 by hand-rolled Q3 (Fraction-pair) Gaussian
# elimination / nullspace. This script re-confirms by TWO independent routes that
# share no code with that recognizer:
#   (A) sympy EXACT symbolic arithmetic over Q(sqrt3) (sqrt(3) kept symbolic),
#       residual identically 0;
#   (B) mpmath HIGH-PRECISION numeric with a_n generated by the deposited
#       REPRODUCE_stokes_2piK.py recursion (dps=160), residual < 1e-120.
# L_V coefficients are transcribed by hand from VQUAD-002 operator-verification.md
# (so a successful zero also validates that human-readable transcription).
#
# L_V = sum_{k=0}^4 p_k(xi) D^k,  D=d/dxi,  p_k(xi)=sum_i p_{k,i} xi^i,
# p_{k,i} = (a,b) meaning a + b*sqrt3.  Annihilation of B-hat=sum_m b_m xi^m means
# for every power xi^N:  res_N = sum_k sum_i p_{k,i} * falling(N-i+k,k) * b_{N-i+k} = 0,
# where b_m = a_{m+1}/m!  and falling(x,k)=x(x-1)...(x-k+1).
import sys as _sys  # bundle portability: force UTF-8 console output
try:
    _sys.stdout.reconfigure(encoding="utf-8")
    _sys.stderr.reconfigure(encoding="utf-8")
except Exception:
    pass
import os
import json
from fractions import Fraction as F
import sympy as sp
import mpmath as mp
import q3_foundation as q3

# --- L_V coefficients, hand-transcribed from operator-verification.md sec 4.0(b) ---
# each entry: list over i (power of xi) of (p, q) with value p + q*sqrt3
LV = {
    0: [(F(1), F(0))],
    1: [(F(659, 431), F(150, 431)), (F(432, 431), F(12, 431))],
    2: [(F(2552175, 418501), F(199224, 418501)),
        (F(496044, 418501),  F(61620, 418501)),
        (F(70092, 418501),   F(3240, 418501))],
    3: [(F(77760, 418501),   F(560736, 418501)),
        (F(1685448, 418501), F(101124, 418501)),
        (F(70092, 418501),   F(3240, 418501))],
    4: [(F(0), F(0)),
        (F(19440, 418501),   F(140184, 418501)),
        (F(210276, 418501),  F(9720, 418501))],
}
ORDER_R = 4

def falling(x, k):
    p = 1
    for t in range(k):
        p *= (x - t)
    return p

# ============================ method A: sympy exact ============================
def a_n_sympy(order):
    """exact a_n in sympy, sourced from the Q3 port (converted to sympy)."""
    a = q3.formal_series_coeffs_exact(order)
    r3 = sp.sqrt(3)
    return [sp.nsimplify(0) + sp.Rational(x.p.numerator, x.p.denominator)
            + sp.Rational(x.q.numerator, x.q.denominator) * r3 for x in a]

def residual_exact(Ns):
    need = max(Ns) + ORDER_R + 2
    a = a_n_sympy(need + 2)
    # b_m = a_{m+1}/m!
    b = [a[m + 1] / sp.factorial(m) for m in range(need)]
    out = {}
    for N in Ns:
        res = sp.Integer(0)
        for k in range(ORDER_R + 1):
            for i, (pp, qq) in enumerate(LV[k]):
                m = N - i + k
                if 0 <= m < len(b):
                    coeff = sp.Rational(pp.numerator, pp.denominator) + \
                            sp.Rational(qq.numerator, qq.denominator) * sp.sqrt(3)
                    res += coeff * falling(m, k) * b[m]
        out[N] = sp.simplify(sp.expand(res))
    return out

# ========================= method B: mpmath numeric ==========================
def a_n_mpmath(order, dps):
    """independent a_n via the deposited REPRODUCE_stokes_2piK.py recursion."""
    mp.mp.dps = dps
    sigma = -1 / mp.sqrt(mp.mpf(3))
    O = order + 12
    c = [mp.mpf(0)] * (O + 1)
    c[0] = sigma
    c[1] = -1 - sigma / 6
    d = [mp.mpf(0)] * (O + 1)
    d[0] = c[0] ** 2
    d[1] = 2 * c[0] * c[1]
    for k in range(2, O + 1):
        known = mp.fsum(c[i] * c[k - i] for i in range(1, k))
        rest = (3 * (known - (k - 1) * c[k - 1]) + d[k - 1] + d[k - 2]
                + 6 * c[k - 1] + c[k - 2])
        c[k] = -rest / (6 * c[0])
        d[k] = 2 * c[0] * c[k] + known - (k - 1) * c[k - 1]
    f = [mp.mpf(0)] * (order + 1)
    for k in range(1, order + 1):
        if k + 1 < len(c):
            f[k] = -c[k + 1] / k
    a = [mp.mpf(0)] * (order + 1)
    a[0] = mp.mpf(1)
    for n in range(1, order + 1):
        a[n] = mp.fsum(k * f[k] * a[n - k] for k in range(1, n + 1)) / n
    return a

def residual_numeric(Ns, dps=160):
    mp.mp.dps = dps
    need = max(Ns) + ORDER_R + 2
    a = a_n_mpmath(need + 2, dps)
    fact = [mp.factorial(m) for m in range(need + 2)]
    b = [a[m + 1] / fact[m] for m in range(need)]
    r3 = mp.sqrt(mp.mpf(3))
    # scale of B-hat near these orders, to report a RELATIVE residual
    out = {}
    for N in Ns:
        res = mp.mpf(0)
        scale = mp.mpf(0)
        for k in range(ORDER_R + 1):
            for i, (pp, qq) in enumerate(LV[k]):
                m = N - i + k
                if 0 <= m < len(b):
                    coeff = mp.mpf(pp.numerator) / pp.denominator + \
                            (mp.mpf(qq.numerator) / qq.denominator) * r3
                    term = coeff * mp.mpf(falling(m, k)) * b[m]
                    res += term
                    scale += abs(term)
        rel = abs(res) / scale if scale != 0 else abs(res)
        out[N] = (res, rel)
    return out

def main():
    Ns = [10, 20, 30, 40, 50]
    print("[A] sympy exact residuals:")
    exact = residual_exact(Ns)
    all_zero = True
    for N in Ns:
        z = (exact[N] == 0)
        all_zero = all_zero and z
        print(f"    res(xi^{N}) = {exact[N]}   zero={z}")

    print("[B] mpmath numeric residuals (dps=160):")
    num = residual_numeric(Ns, dps=160)
    worst_rel = mp.mpf(0)
    for N in Ns:
        res, rel = num[N]
        worst_rel = max(worst_rel, rel)
        print(f"    res(xi^{N}) rel = {mp.nstr(rel, 4)}")

    result = {
        "Ns": Ns,
        "method_A": "sympy exact symbolic over Q(sqrt3)",
        "method_A_all_identically_zero": bool(all_zero),
        "method_B": "mpmath numeric dps=160, a_n via deposited REPRODUCE_stokes_2piK recursion",
        "method_B_worst_relative_residual": mp.nstr(worst_rel, 6),
        "LV_source": "VQUAD-002 operator-verification.md sec 4.0(b) (hand-transcribed)",
        "verdict": "CONFIRMED" if (all_zero and worst_rel < mp.mpf(10) ** (-100)) else "DISCREPANCY",
    }
    path = (os.path.join(os.path.dirname(os.path.abspath(__file__)), "stage0_residual_results.json"))
    with open(path, "w", encoding="utf-8") as fh:
        json.dump(result, fh, indent=2)
    print("\n[verdict]", result["verdict"])
    print("[wrote]", path)

if __name__ == "__main__":
    main()
