"""
verify_pi_outside_W_aff.py
==========================

Symbolic verification (sympy) of the negative-finding chain
established in Phase A:

  (i)   s : (v_1, v_2) -> (-v_1 - 2, v_2)         (Okamoto 1987 §1.3 (ii))
        is the closest §§3+ candidate to
        pi : (v_1, v_2) -> (-1 - v_1, v_2).

  (ii)  pi = s o T_{(-1, 0)} where T_{(-1, 0)}: v_1 -> v_1 - 1.

  (iii) T_{(-1, 0)} is in P^v(B_2) but NOT in Q^v(B_2),
        which means pi is NOT in W^aff(B_2) = W(B_2) x| Q^v(B_2).

  (iv)  pi^2 = identity (involution check).

The script extends 033's verify_homomorphism.py spirit by adding
a separate involution-check on pi alone and a coroot-lattice
membership test on the residual translation.
"""
import sympy as sp


def main():
    v1, v2 = sp.symbols("v1 v2", complex=True)

    # --- (i)  s and pi action on (v_1, v_2) ---
    def s(v):           # Okamoto 1987 §1.3 (ii)
        a, b = v
        return (-a - 2, b)

    def pi_target(v):   # spec primary target
        a, b = v
        return (-1 - a, b)

    def T_minus_e1(v):  # T_{(-1, 0)}
        a, b = v
        return (a - 1, b)

    v0 = (v1, v2)

    # --- (ii)  pi = s o T_{(-1, 0)}  ---
    lhs = pi_target(v0)
    rhs = s(T_minus_e1(v0))
    print("Check (ii):  pi(v) == s(T_{(-1,0)}(v))?")
    print("  LHS = pi(v)            =", lhs)
    print("  RHS = s(T(-1,0)(v))    =", rhs)
    print("  match:", lhs == rhs)
    print()

    # --- (iii)  Q^v(B_2) membership test for translation lambda ---
    # Q^v(B_2) = Z * alpha_1^v + Z * alpha_2^v
    #         = Z * (e_1 - e_2) + Z * (2 e_2)
    # Generic element:  lambda = (m, 2n - m)  for m, n in Z.
    #
    # Test:  lambda = (-1, 0)?  Need m = -1, 2n - m = 0 -> n = -1/2.
    m_var, n_var = sp.symbols("m n", integer=True)
    target = sp.Matrix([-1, 0])
    rep = sp.Matrix([m_var, 2 * n_var - m_var])
    sol = sp.solve(rep - target, [m_var, n_var], dict=True)
    print("Check (iii):  Is T_{(-1, 0)} in Q^v(B_2)?")
    print("  Q^v generic: lambda = (m, 2n-m), m,n integers.")
    print("  Solving (m, 2n-m) = (-1, 0):")
    print("    sol =", sol)
    if sol:
        n_val = sol[0].get(n_var)
        is_int = (n_val is not None) and n_val.is_Integer
        print("  n =", n_val, "  integer?", bool(is_int))
        print("  -> T_{(-1, 0)} in Q^v(B_2):", bool(is_int))
    print()

    # Cross-check: lambda = (1, 1) and (1, -1) (the two l, l~ shifts) ARE in Q^v.
    for tgt in [(1, 1), (1, -1)]:
        target_t = sp.Matrix(list(tgt))
        sol_t = sp.solve(rep - target_t, [m_var, n_var], dict=True)
        n_val = sol_t[0][n_var] if sol_t else None
        is_int = (n_val is not None) and sp.simplify(n_val).is_Integer
        print("  Cross-check: T_{} in Q^v? sol = {}, integer? {}".format(
            tgt, sol_t, bool(is_int)))
    print()

    # --- (iv)  pi is an involution: pi^2 = id ---
    pi_squared = pi_target(pi_target(v0))
    print("Check (iv):  pi^2 = id ?")
    print("  pi^2(v) =", pi_squared)
    print("  match identity:", pi_squared == v0)
    print()

    # --- (v)  P^v(B_2) generic element check ---
    # P^v(B_2) is generated by the fundamental coweights.  For B_2:
    #   omega_1^v = e_1
    #   omega_2^v = (e_1 + e_2) / 2     (corresponds to short coroot)
    # WAIT - careful normalization.  Standard B_2 coroots/coweights:
    #   alpha_1 long  -> alpha_1^v = alpha_1 = e_1 - e_2;
    #     omega_1^v dual to alpha_1: <omega_1^v, alpha_1> = 1, etc.
    # Equivalent shortcut:  P^v(B_2) = lattice in R^2 generated
    # by (1, 0) and (0, 1) -- it is just Z^2 in this normalization.
    # Q^v(B_2) is the index-2 sublattice {(a, b) in Z^2 : a + b even}.
    print("Check (v):  P^v(B_2) / Q^v(B_2) classification.")
    print("  In Okamoto basis (e_1, e_2) with (e_i|e_j) = delta_ij,")
    print("  Q^v(B_2) = Z(1,-1) + Z(0,2) = {(a,b) in Z^2 : a+b even}.")
    print("  P^v(B_2) = Z^2.")
    print("  Index = 2.")
    print()
    cosets = [(0, 0), (1, 0), (0, 1), (1, 1)]
    for c in cosets:
        a, b = c
        in_Qv = ((a + b) % 2 == 0)
        print("    (a,b)=({},{}): a+b even? {} -> in Q^v? {}".format(
            a, b, (a + b) % 2 == 0, in_Qv))
    print()
    print("  T_{(-1, 0)} = (-1, 0):  -1 + 0 = -1 odd -> NOT in Q^v.  Confirmed.")
    print("  T_{(1, 1)}  = ( 1, 1):   1 + 1 = 2  even -> in Q^v.  l shift OK.")
    print("  T_{(1, -1)} = ( 1,-1):   1 - 1 = 0  even -> in Q^v.  l~ shift OK.")
    print()

    print("CONCLUSION:  pi is in W^ext(B_2) = W(B_2) x| P^v(B_2)")
    print("but NOT in W^aff(B_2) = W(B_2) x| Q^v(B_2).")
    print("This affirms 033's index-2 finding at the lattice-theory level.")


if __name__ == "__main__":
    main()
